Validate inputs for questions endpoints
CS3219-AY2425S1/cs3219-ay2425s1-project-g20 pull request #18
Opened 2024-09-27 07:07 UTC by donljh

2024-09-27 07:14 UTC, asaierika submitted a review, later dismissed
LGTM

2024-09-27 11:39 UTC, ys112 requested changes
Code looks good to me. However, I think we have to implement duplicate check too under task 7. For frontend, I did a simple title check to fulfil this requirement. 

![image](https://github.com/user-attachments/assets/de902224-62b8-45d4-bb22-8807380119b2)

2024-09-28 10:34 UTC, bachletuankhai commented on services/question/src/routes/questions.ts
> +  const parsedRequestBody = questionSchema.partial().safeParse(req.body)
Can you ensure that at least 1 property must present?
[https://stackoverflow.com/questions/73281501/at-least-one-minimum-one-field-in-zod-schema-validation](https://stackoverflow.com/questions/73281501/at-least-one-minimum-one-field-in-zod-schema-validation)

2024-09-28 12:58 UTC, ys112 approved these changes

2024-09-28 12:59 UTC, bachletuankhai approved these changes
LGTM

2024-09-28 12:59 UTC, merged